#[cfg(windows)] pub mod screenshot;
#[cfg(windows)] pub mod input;
#[cfg(windows)] pub mod window;
#[cfg(windows)] pub mod app;
#[cfg(windows)] pub mod app_index;
pub mod bridge;
#[cfg(windows)] pub mod capture;
#[cfg(windows)] pub mod gdi_utils;
pub mod image_process;
pub mod file_util;
#[cfg(windows)] pub mod global_listener;
pub mod global_state;
